package frc.robot.subsystems;

public enum TowerState {
	//Start
	INIT,
	MAKING_WRIST_SAFE,
	HOMING_ELEVATOR,
	HOMING_WRIST,
	HOME,

	//Scoring
	INTAKING,
	INTAKE_PAUSE,
	GOING_TO_SAFE,
	GOT_CORAL,
	RAISING_TO_L123,
	READY_TO_SCORE_CORAL,
	RAISING_TO_L4,
	TILTING_TO_SCORE_L4, // L4
	SCORING_CORAL,
	

	//Algae
	GET_SAFE_FOR_L2_ALGAE,
	GET_SAFE_FOR_L3_ALGAE,
	GOING_TO_ALGAE_INTAKE,
	WAITING_FOR_ALGAE,
	CHANGING_ALGAE_HEIGHT,
	PAUSING_AFTER_SCORING_ALGAE,

	WINDING_UP,
	RELEASING,

	//Returning
	PAUSING_AFTER_SCORING_CORAL,
	LOWERING,
	GOING_TO_CORAL_INTAKE_ANGLE
}
